### PR TITLE
adds extra else just in case nothing was selected as default

### PR DESCRIPTION
**Pull request by ablwr**
prevents nil

### CODE REVIEW

**Review by privatezero — COMMENTED** [review]
Should have been declared in https://github.com/amiaopensource/audiorecorder/blob/master/audiorecorder2-dev/audiorecorder2/audiorecorder2.rb#L27 ?

**Comment by ablwr** [comment]
Oh yeah I guess I figured those were temporarily loaded just for testing!

**Comment by ablwr** [comment]
feel free to close

**Comment by privatezero** [comment]
Right now those are loaded so things don't freak out the first time someone runs the program in terms of establishing what the drop downs will be set to!

**Comment by privatezero** [comment]
(since the drop downs default to their previous saved value)

**Pull request closed without merging**
