### PR TITLE
add channel options to legacy gui

### PR DESCRIPTION
**Pull request by privatezero**
I don't have a four channel A/D converter so can't test, but I think this ought to help with situations like https://github.com/amiaopensource/audiorecorder/issues/73

### CODE REVIEW

**Comment by bturkus** [comment]
hey. thanks for adding this! I'm feeling stupid, but I'm having trouble testing. It's been merged, but when I upgrade I'm getting:
```
Error: amiaopensource/amiaos/audiorecorder 0.1.08 already installed
```
why no changey?

**Comment by privatezero** [comment]
I haven't made a new release yet, so `brew upgrade` is still pointed at the existing release (that doesn't have the new option). I'll push out a new release this morning so it should work via homebrew soon!

**Comment by privatezero** [comment]
@bturkus, should be cooking with gas now! Again, wasn't actually able to live test that patch, so lemme know if there are any problems! Also, wanted to point out this FFmpeg related quirk https://github.com/amiaopensource/audiorecorder/issues/76 so you don't waste a ton of time checking your cables for reversed polarity like I did >:-|

**Comment by bturkus** [comment]
happy to report this is working perfectly! thanks again for all the help. audiorecorder's so cool!

**Pull request merged**
