### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by privatezero**
Still very much a work in progress, but I thought I would move over the development of the 'Shoes' based GUI controlled audiorecorder2.

Currently there is a partially formatted semi-functional GUI in Linux, and a GUI that will load but doesn't actually do anything in macOS.

### CODE REVIEW

**Comment by privatezero** [comment]
This is what we have so far - all buttons work in Linux, except the BWF one just opens a window to nowhere. Options also are still in ffmpeg and not human formatting.

image

**Comment by ablwr** [comment]
SOOOOO CUUUUTTTTEEEE!!!!!!!!!!!!!!!!!!!!!!!

**Comment by todrobbins** [comment]
@privatezero I want to make that tape into an animated GIF for the app. Will you send the source file so I can get my groove on?

**Comment by privatezero** [comment]
Hi @todrobbins - there is a larger and smaller version of the file buried in the [resources page](https://github.com/amiaopensource/audiorecorder/tree/master/audiorecorder2-dev/audiorecorder2/Resources)! That would be rad if you giffed it up! 

Also, there are most likely going to be 2~3 windows in the final GUI, with a main window, a window for BEXT information and a Post Processing window. I had been kicking around ideas of either having different images for each window - either more pixel style images of different analog audio carriers, or maybe just more cassettes with different colors/labels. If you have any ideas, fire away!!

**Comment by privatezero** [comment]
Also, just confirmed that GIFs are one of the image formats accepted by Shoes! http://shoesrb.com/manual/Image.html

**Pull request merged**
