### PR TITLE
added first draft animated logo

### PR DESCRIPTION
**Pull request by todrobbins**
What do you think?

audiorecorder_play_large

### CODE REVIEW

**Review by dericed — APPROVED** [review]
just going to watch this until the end of the day

**Comment by privatezero** [comment]
OMG I love it!!! I am with Dave - you totally just ruined my productivity for today. Mesmerisedddddddd

**Comment by todrobbins** [comment]
Two frames, y'all!

**Comment by privatezero** [comment]
The smaller version isn't animating on my end - is that just my machine?

**Comment by todrobbins** [comment]
It works on my filesystem (macOS), but when I try to upload it as a comment (for instance), it's frozen:

audiorecorder_play_small

Hrmmm... Let me try exporting the small one again.

**Comment by todrobbins** [comment]
@privatezero should be fixed now.

**Comment by privatezero** [comment]
Lovin' it!! Thank you soooo much!

**Comment by todrobbins** [comment]
PS: what did you use to draw the initial pixel image?

**Comment by privatezero** [comment]
I actually just did it with an in browser tool! https://www.pixilart.com/

**Comment by privatezero** [comment]
(I totally had to look at other pixel art cassettes and freehand imitate one)

**Pull request merged**
