### PR TITLE
Changes for macos

### PR DESCRIPTION
**Pull request by privatezero**
This is still less refined than would ultimately be nice, but these changes should make audiorecorder functional on a mac that has installed dependencies via homebrew

### CODE REVIEW

**Review by ablwr — APPROVED** [review]
Hey! It records. Trim and Preview don't seem to be working yet.

**Comment by privatezero** [comment]
Do you have all the dependencies (ffmpeg/probe/play, sox and mpv) installed on the usual homebrew paths?

**Comment by ablwr** [comment]
No

**Comment by ablwr** [comment]
Whoops, actually yes

**Comment by privatezero** [comment]
Gonna merge this for now - we can work out some refinements in  a future pull

**Pull request merged**
