### PR TITLE
test for ffmpeg version (change avectorscope)

### PR DESCRIPTION
**Pull request by privatezero**
This should resolve issue of non-standard avectorscope orientation in FFmpeg 4.0 and 4.0.1

### CODE REVIEW

**Comment by privatezero** [comment]
Looks like this isn't totally happy in macOS - needs a slight change

**Comment by retokromer** [comment]
The current version is 4.0.2 (and it changes regularly). I guess, you need ≥ 4 and would better trap only the number until the period.

**Comment by privatezero** [comment]
Hi @retokromer! Sadly that's what I was doing originally, using back-ticks to make the system call to ffmpeg withing ruby and then parsing the output for the version being > 4. This method appears to have some problems once it is packaged as a macOS app where although paths that are external to the app (such as ffmpeg) work well with being called by `system('command')` they were failing with the back-ticks. 

This is problematic as using `system()` returns `True` or `False` rather than the standard out of the command, thus causing me to experiment with a workaround that will work under those constraints until a better solution is found! (Also since the filter has already been fixed in HEAD, I am hoping it will be incorporated into a release of FFmpeg soon).

I haven't tested this yet on macOS to even see if this is even a viable temporary fix though! It also will not help in the context of capturing the `silencedetect` outputs later on in the script. If I can't think of a better way I was thinking of possibly using `system(ffmpeg...)` and having it dump its output to a temp file that could then be parsed internally in ruby. All suggestions/advice for a more elegant solution are welcome!

**Comment by retokromer** [comment]
> All suggestions/advice for a more elegant solution are welcome!

Thank you, @privatezero, for the explanation! I’m not really Ruby skilled myself, but I’ll try to find an elegant solution.

**Comment by privatezero** [comment]
The problem really all comes down with the paths inside the macOS app structure once it is packaged via Shoes, so if we could find an elegant/reliable way to get these external paths to be recognized that would solve pretty much all the issues! Everything else I have done is basically a hacky way to try to work around this. So not even necessarily a ruby issue, just me not quite understanding how mac apps work.

Right now paths are hard-coded (which is also not optimal) and apparently still doesn't work with using the back-tick method to call them (although works with `system()`). I am also trying to avoid having to embed FFmpeg within the app itself.

This is the primary hold-up for me getting this all working across platforms, as otherwise things are working fine!

**Comment by privatezero** [comment]
These tweaks have this working for now - will merge and continue to look for improved options

**Comment by retokromer** [comment]
+1

**Review by retokromer — APPROVED** [review]
LGTM

**Comment by privatezero** [comment]
Thanks @retokromer! I will now take a stab at adapting the auto trim function, which I suspect is subject to the same problem.

**Comment by privatezero** [comment]
Did a bit of follow up, the necessary data for trim I was worried about in fact was working - will need to test a bit more with actual analogue material, but for now that worry seems ok.

**Pull request merged**
