### PR TITLE
adds linebreaks to option selection

### PR DESCRIPTION
**Pull request by ablwr**
Just gonna keep throwing code changes at you, feel free to ignore!!!!

### CODE REVIEW

**Comment by privatezero** [comment]
Looks good!

**Comment by retokromer** [comment]
Hello @privatezero, do you plan to make a release of v2 in the next two weeks or so? (We’ll have a two-days workshop on open source beginning of April in Bangkok…)

**Comment by privatezero** [comment]
Hi @retokromer! v2 is chugging along, and is basically fully functional in linux - I still have work to do to make it functional in macOS. Although it is functional in a rough form, as I am still working on lots of necessary refinements, I haven't had time to do any actual stress tests and QC any test captures to make sure everything is functioning as expected.

As such, I would be a little hesitant to release it for archival use just quite yet, so I hadn't been planning on pushing an official release - I wouldn't be opposed to making a conditional release though if it would be helpful!

**Comment by retokromer** [comment]
Thank you, @privatezero, for the information! That makes sense. We‘ll wait two weeks, and decide only at the last moment to use either v1 or v2 for the workshop. (And if v1, we can anyways mention that v2 is around the corner.)

**Comment by mcampos-quinn** [comment]
We are super stoked on this pending update, @privatezero .... really good timing with a workflow revamp for our cassette digitization!

**Comment by privatezero** [comment]
thanks @mcampos-quinn! Let me know if you have any requests/suggestions!

**Comment by ablwr** [comment]
@mcampos-quinn is the best!

**Comment by privatezero** [comment]
@retokromer - Following up since I see a lot of releases being made, so I assume you are getting ready for your workshop!

I have tested a bit and (and have another test recording I still need to run through wavelab analysis). Core functions seem to be working fine - I have come across some user experience issues as noted in https://github.com/amiaopensource/audiorecorder/issues/66. These aren't critical, but I would say that version 2 is close but not quite ready for an official release!

Probably mentioning that it is impending, but not quite there yet is the best plan!

**Comment by retokromer** [comment]
Thank you, @privatezero, for the information!

**Pull request merged**
